# Generated by Django 5.1.dev20231109130319 on 2023-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedlist',
            name='Location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
