# Generated by Django 5.1.dev20231109130319 on 2023-11-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndList', '0002_remove_searchedtag_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedtag',
            name='searchedLocation',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
