# Generated by Django 5.1.dev20231109130319 on 2023-11-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndList', '0002_searchedlist_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedlist',
            name='Location',
        ),
        migrations.AlterField(
            model_name='searchedlist',
            name='Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_lists', to='SearchAndList.searchedtag'),
        ),
        migrations.AddConstraint(
            model_name='searchedtag',
            constraint=models.UniqueConstraint(fields=('searchedTag_text', 'searchedLocation_text'), name='unique_set'),
        ),
        migrations.AddField(
            model_name='searchedlist',
            name='location',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
