# Generated by Django 5.1.dev20231109130319 on 2023-11-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndList', '0003_searchedtag_searchedlocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchedtag',
            unique_together={('searchedTag_text', 'searchedLocation')},
        ),
    ]
