# Generated by Django 5.1.dev20231109130319 on 2023-11-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndList', '0005_alter_searchedtag_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedtag',
            name='id',
        ),
        migrations.AlterField(
            model_name='searchedlist',
            name='Tag',
            field=models.ForeignKey(db_column=['searchedTag_text', 'searchedLocation'], on_delete=django.db.models.deletion.CASCADE, to='SearchAndList.searchedtag'),
        ),
        migrations.AlterField(
            model_name='searchedtag',
            name='searchedTag_text',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
